artifacts_root: artifacts

# Data fetching config
data_fetch:
  root_dir: artifacts/data_fetch
  ticker: "AAPL"
  period: "5y"
  start_date: "2020-01-01"
  end_date: "2024-12-31"
  output_file: artifacts/data_fetch/apple.csv


data_storage:
  root_dir: artifacts/data_storage
  db_url: "postgresql://admin:admin@localhost:5432/apple_db"
  table_name: "apple_stock_data"


langchain:
  llm_provider: "deepseek"
  llm_model: "deepseek-r1-distill-llama-70b"
  temperature: 0.7
  prompt_template: |
    You are an assistant that generates SQL queries based on natural language questions.
    Given the following question, produce a valid SQL query for the provided database.
    Question: {question}
    SQL Query:

  db_url: "postgresql://user:password@localhost:5432/database"
  table_name: "stocks"